class Global {
  static int index = 0;
  static List<Map<String, dynamic>> questionAns = [
    {
      'no': 1,
      'q': 'Which day is observed as the World Standards Day?',
      'A': 'June 26',
      'B': 'Oct 14',
      'C': 'Nov 15',
      'D': 'Dec 2',
      'ans': 'B',
      'price': 10000,
    },
    {
      'no': 2,
      'q': 'Who is the author of Manas Ka-Hans ?',
      'A': 'Khushwant Singh',
      'B': 'Prem Chand',
      'C': 'Jayashankar Prasad',
      'D': 'Amrit Lal Nagar',
      'ans': 'D',
      'price': 20000,
    },
    {
      'no': 3,
      'q': 'Who is the author of the epic Meghdoot ?',
      'A': 'Kalidas',
      'B': 'Valmiki',
      'C': 'Banabhatta',
      'D': 'Vishakadatta',
      'ans': 'A',
      'price': 30000,
    },
    {
      'no': 4,
      'q': 'Which of the following is observed as Sports Day every year ?',
      'A': '22nd April',
      'B': '26th  july',
      'C': '29th August',
      'D': '2nd October',
      'ans': 'C',
      'price': 40000,
    },
    {
      'no': 5,
      'q': 'Pongal is a popular festival of which state ?',
      'A': 'Karnataka',
      'B': 'Kerala',
      'C': 'Tamil Nadu',
      'D': 'Andhra Pradesh',
      'ans': 'C',
      'price': 50000,
    },
    {
      'no': 6,
      'q': 'Which of the following is not a dance from Kerala ?',
      'A': 'Yaksha Gana',
      'B': 'Kathakali',
      'C': 'Mohiniattam',
      'D': 'Ottan Thullal',
      'ans': 'A',
      'price': 60000,
    },
    {
      'no': 7,
      'q': 'When Was the Indian Peace Keeping Force Sent to Sri Lanka ?',
      'A': 'May,1986',
      'B': 'July,1987',
      'C': 'May,1988',
      'D': 'March, 1990',
      'ans': 'B',
      'price': 70000,
    },
    {
      'no': 8,
      'q': 'Of which of the following states is Nautanki, a folk dance ?',
      'A': 'Orissa',
      'B': 'Meghalaya',
      'C': 'Arunachal Pradesh',
      'D': 'Uttar Pradesh',
      'ans': 'D',
      'price': 80000,
    },
    {
      'no': 9,
      'q':
          'Which of the following folk dance forms is associated with Gujarat ?',
      'A': 'Nautanki',
      'B': 'Bhangra',
      'C': 'Garba',
      'D': 'Kathakal',
      'ans': 'C',
      'price': 90000,
    },
    {
      'no': 10,
      'q': 'Who composed  the famous song  Sare Jhan Se Achha  ?',
      'A': 'Bankim Chandra Chatterjee',
      'B': 'Mohammad Iqbal',
      'C': 'Jaidev',
      'D': 'Rabindra Nath Tagore',
      'ans': 'B',
      'price': 100000,
    },
  ];
}
